# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tda' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  
  # Pods for tda
  # rnc for user camera upload
  pod 'react-native-camera', path: '../node_modules/react-native-camera'

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # target 'tda-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'tdaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'tda-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for tda-tvOS

#   target 'tda-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

end
