// page load
export const LOGIN_PAGE_LOADING = 'LOGIN_PAGE_LOADING';
export const LOGIN_PAGE_LOADED = 'LOGIN_PAGE_LOADED';
export const LOGIN_PAGE_FAIL = 'LOGIN_PAGE_FAIL';

// firebase logging in
export const USER_LOGGING_IN = 'USER_LOGGING_IN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const FIREBASE_LOGIN_STARTED = 'FIREBASE_LOGIN_STARTED';

// firebase registering
export const REG_PAGE_LOADED = 'REG_PAGE_LOADED';
export const REG_PAGE_LOADING = 'REG_PAGE_LOADING';
export const USER_REGISTERING = 'USER_REGISTERING';
export const USER_REGISTRATION_FAIL = 'USER_REGISTRATION_FAIL';
export const RESET_REGPAGE_STATE = 'RESET_REGPAGE_STATE';
// Async Storage
export const SAVING_UID_TO_ASYNC_STORAGE = 'SAVING_UID_TO_ASYNC_STORAGE';


