// page load
export const LOGIN_PAGE_LOADING = 'LOGIN_PAGE_LOADING';
export const LOGIN_PAGE_LOADED = 'LOGIN_PAGE_LOADED';
export const LOGIN_PAGE_FAIL = 'LOGIN_PAGE_FAIL';

// firebase logging in
export const USER_LOGGING_IN = 'USER_LOGGING_IN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const FIREBASE_LOGIN_STARTED = 'FIREBASE_LOGIN_STARTED';

// Async Storage
export const SAVING_UID_TO_ASYNC_STORAGE = 'SAVING_UID_TO_ASYNC_STORAGE';


